const API_URL = (window.__PUB_API_URL__ || 'http://127.0.0.1:3000').replace(/\/$/, '');
const state = { pubs: [], filtered: [], aiResults: null, aiContext: null, aiOffset: 0, recommendationsExpanded: false, visited: new Set(JSON.parse(localStorage.getItem('pub-discovery-visited') || '[]')), saved: new Set(JSON.parse(localStorage.getItem('pub-discovery-saved') || '[]')), query: '', view: 'list', map: null, markers: null };
const $ = (selector) => document.querySelector(selector);

function persist() { localStorage.setItem('pub-discovery-visited', JSON.stringify([...state.visited])); localStorage.setItem('pub-discovery-saved', JSON.stringify([...state.saved])); updateCounts(); }
function updateCounts() { $('#nav-visited-count').textContent = state.visited.size; $('#visited-total').textContent = state.visited.size; $('#saved-total').textContent = state.saved.size; $('#discovered-total').textContent = state.pubs.length; const percent = state.pubs.length ? Math.round(state.visited.size / state.pubs.length * 100) : 0; $('#passport-percent').textContent = `${percent}%`; $('#progress-label').textContent = `${percent}% complete`; $('#progress-fill').style.width = `${percent}%`; }
function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); window.clearTimeout(toast.timer); toast.timer = window.setTimeout(() => el.classList.remove('show'), 2400); }
function safeUrl(value) { try { const url = new URL(value); return ['http:', 'https:'].includes(url.protocol) ? url.href : null; } catch { return null; } }
function normalizedTags(pub) { return Object.entries(pub.tags || {}).filter(([, value]) => value).map(([key, value]) => `${key} ${value}`.toLowerCase()).join(' '); }
function areaFor(pub) { const text = `${pub.address || ''} ${normalizedTags(pub)}`; if (/camden/i.test(text)) return 'Camden'; if (/westminster|soho|mayfair|pimlico/i.test(text)) return 'Westminster'; return 'London'; }
function areaFromQuery(query) { return ['Camden', 'Westminster', 'Waterloo', 'London Bridge', 'Shoreditch', 'Brixton'].find((area) => query.toLowerCase().includes(area.toLowerCase())) || null; }
function applyFilter() { const query = state.query.trim().toLowerCase(); const literalMatches = state.pubs.filter((pub) => !query || `${pub.name} ${pub.address || ''} ${normalizedTags(pub)}`.toLowerCase().includes(query)); const area = areaFromQuery(query); state.filtered = literalMatches.length || !area ? literalMatches : state.pubs.filter((pub) => areaFor(pub).toLowerCase() === area.toLowerCase()); if (query && !literalMatches.length && area) $('#status').textContent = `No exact matches for that request · showing ${area} pubs while verified details are checked`; renderResults(); }

function card(pub, options = {}) {
  const recommended = options.recommended;
  const wrapper = document.createElement('article'); wrapper.className = `pub-card${recommended ? ' recommended' : ''}`;
  const top = document.createElement('div'); top.className = 'pub-top';
  const heading = document.createElement('div'); const title = document.createElement('h3'); title.className = 'pub-name'; title.textContent = pub.name; heading.append(title);
  const address = document.createElement('p'); address.className = 'pub-address'; address.textContent = `${areaFor(pub)} · ${pub.address || 'Address available on map'}`; heading.append(address); top.append(heading);
  wrapper.append(top);
  const facts = document.createElement('div'); facts.className = 'pub-facts'; const explanation = (options.reasons?.[0] || '').toLowerCase(); const tags = [...(pub.verifiedFeatures || []), ...Object.values(pub.tags || {})].map((tag) => String(tag).replaceAll('_', ' ').replace(/\s+/g, ' ').trim()).filter((tag) => /food|music|dj|outdoor|sports|dog|historic|event|accessible|roast|vegan|quiz/i.test(tag) && !explanation.includes(tag.toLowerCase())); const uniqueTags = [...new Map(tags.map((tag) => [tag.toLowerCase(), tag])).values()].slice(0, 4); uniqueTags.forEach((tag) => { const fact = document.createElement('span'); fact.className = 'fact'; fact.textContent = tag; facts.append(fact); }); if (!facts.children.length && !explanation) { const fact = document.createElement('span'); fact.className = 'fact'; fact.textContent = 'London pub'; facts.append(fact); } wrapper.append(facts);
  if (options.reasons?.length) { const note = document.createElement('p'); note.className = 'pub-note'; note.textContent = options.reasons[0]; wrapper.append(note); }
  const actions = document.createElement('div'); actions.className = 'card-actions';
  const visit = document.createElement('button'); visit.className = `visit-button${state.visited.has(pub.id) ? ' visited' : ''}`; visit.textContent = state.visited.has(pub.id) ? '✓ Visited' : 'Mark visited'; visit.onclick = () => { state.visited.has(pub.id) ? state.visited.delete(pub.id) : state.visited.add(pub.id); persist(); renderAll(); toast(state.visited.has(pub.id) ? 'Added to your passport' : 'Removed from passport'); }; actions.append(visit);
  const save = document.createElement('button'); save.className = `save-button${state.saved.has(pub.id) ? ' saved' : ''}`; save.textContent = state.saved.has(pub.id) ? '♥ Saved' : '♡ Save'; save.onclick = () => { state.saved.has(pub.id) ? state.saved.delete(pub.id) : state.saved.add(pub.id); persist(); renderAll(); toast(state.saved.has(pub.id) ? 'Saved for later' : 'Removed from saved'); }; actions.append(save);
  const details = document.createElement('button'); details.textContent = 'Details'; details.onclick = () => showDetails(pub, options); actions.append(details); wrapper.append(actions); return wrapper;
}

function aiPub(item) { const pub = state.pubs.find((candidate) => candidate.id === item.venueId); return pub ? { ...pub, verifiedFeatures: item.verifiedFeatures || pub.verifiedFeatures } : { id: item.venueId, name: item.name, latitude: item.latitude, longitude: item.longitude, address: item.address, website: item.website, phone: item.phone, tags: {}, verifiedFeatures: item.verifiedFeatures || [] }; }
function visiblePubs() { return state.aiResults === null ? state.filtered : state.aiResults.map(aiPub); }
function renderResults() { const container = $('#results'); container.replaceChildren(); const aiMode = state.aiResults !== null; $('#results-title').textContent = aiMode ? `AI recommendations for “${state.query}”` : state.query ? `Browse results for “${state.query}”` : 'Browse all pubs'; if (aiMode) { if (!state.aiResults.length) { const empty = document.createElement('div'); empty.className = 'empty-state'; empty.textContent = state.aiContext?.noResultReasons?.[0] || 'No verified matches for that request yet. Try a broader search.'; container.append(empty); return; } const visibleResults = state.recommendationsExpanded ? state.aiResults : state.aiResults.slice(0, 6); visibleResults.forEach((item) => container.append(card(aiPub(item), { recommended: true, reasons: item.reasons }))); if (state.aiResults.length > 6 || state.aiContext?.hasMore) { const more = document.createElement('button'); more.className = 'view-more-button'; more.textContent = state.recommendationsExpanded ? 'View less' : 'View more recommendations'; more.onclick = () => { if (state.recommendationsExpanded) { state.recommendationsExpanded = false; renderResults(); } else if (state.aiContext?.hasMore) void getRecommendations(state.aiResults.length, true); else { state.recommendationsExpanded = true; renderResults(); } }; container.append(more); } } else { if (!state.filtered.length) { const empty = document.createElement('div'); empty.className = 'empty-state'; empty.textContent = 'No pubs are available to browse yet.'; container.append(empty); return; } state.filtered.slice(0, 60).forEach((pub) => container.append(card(pub))); } if (state.view === 'map') renderMap(); }
function renderSuggestions(data) { const container = $('#suggestion-chips'); container.replaceChildren(); const suggestions = [['Live music', 'pub with live music'], ['Live sport', 'pub showing live sport'], ['Food', 'pub with food'], ['Outdoor seating', 'pub with outdoor seating'], ['Dog friendly', 'dog-friendly pub'], ['Sunday roast', 'pub serving a Sunday roast'], ['Quiz night', 'pub with a quiz night']]; const detected = [...(data?.recommendations || [])].flatMap((item) => item.verifiedFeatures || []).map((item) => item.toLowerCase()); suggestions.filter(([label]) => detected.some((feature) => feature.includes(label.toLowerCase().split(' ')[0]))).slice(0, 4).forEach(([label, query]) => { const button = document.createElement('button'); button.textContent = `Try ${label}`; button.onclick = () => { $('#query').value = query; state.query = query; void getRecommendations(); }; container.append(button); }); container.hidden = !container.children.length; }
function renderPassport() { const container = $('#passport-list'); container.replaceChildren(); const visited = state.pubs.filter((pub) => state.visited.has(pub.id)); if (!visited.length) { const empty = document.createElement('div'); empty.className = 'empty-state'; empty.textContent = 'Your passport is ready. Explore a pub and mark it visited to collect your first stamp.'; container.append(empty); } else visited.forEach((pub) => container.append(card(pub))); }
function renderAll() { updateCounts(); renderResults(); renderPassport(); }

function showDetails(pub, options = {}) { const content = $('#detail-content'); content.replaceChildren(); const inner = document.createElement('div'); inner.className = 'detail-inner'; const eyebrow = document.createElement('p'); eyebrow.className = 'eyebrow'; eyebrow.textContent = options.recommended ? 'PERSONAL PICK' : areaFor(pub).toUpperCase(); inner.append(eyebrow); const title = document.createElement('h2'); title.textContent = pub.name; inner.append(title); const address = document.createElement('p'); address.className = 'pub-address'; address.textContent = pub.address || 'Address available on map'; inner.append(address); const body = document.createElement('div'); body.className = 'detail-body'; [['Area', areaFor(pub)], ['Opening hours', pub.openingHours || 'Not verified'], ['Website', pub.website || 'Not listed'], ['Phone', pub.phone || 'Not listed']].forEach(([label, value]) => { const row = document.createElement('div'); row.className = 'detail-row'; const left = document.createElement('span'); left.textContent = label; const right = document.createElement('strong'); if (label === 'Website' && safeUrl(value)) { const link = document.createElement('a'); link.href = safeUrl(value); link.target = '_blank'; link.rel = 'noopener'; link.textContent = 'Open website ↗'; right.append(link); } else right.textContent = value; row.append(left, right); body.append(row); }); inner.append(body); content.append(inner); $('#detail-dialog').showModal(); }
async function getRecommendations(offset = 0, append = false) { const query = state.query.trim(); if (!query) { toast('Tell us what kind of pub you want first'); return; } if (!append) state.recommendationsExpanded = false; $('#status').textContent = append ? 'Finding more matches…' : 'AI is finding the best verified matches…'; try { const response = await fetch(`${API_URL}/recommendations`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query, limit: 6, offset }) }); if (!response.ok) throw new Error(); const data = await response.json(); state.aiResults = append ? [...state.aiResults, ...(data.recommendations || [])] : (data.recommendations || []); state.aiContext = data; state.aiOffset = offset; renderSuggestions(data); $('#status').textContent = state.aiResults.length ? `${state.aiResults.length} thoughtful matches found` : 'No verified matches found'; renderResults(); } catch { $('#status').textContent = 'Search is unavailable right now'; toast(`Could not reach the AI recommendation service at ${API_URL}`); } }
async function loadPubs() { try { const response = await fetch(`${API_URL}/pubs?limit=2000`); if (!response.ok) throw new Error(); const data = await response.json(); state.pubs = data.pubs || []; state.filtered = state.pubs; $('#status').textContent = `${state.pubs.length} pubs ready to explore`; renderAll(); } catch { try { const response = await fetch('sample-pubs.json'); state.pubs = await response.json(); state.filtered = state.pubs; $('#status').textContent = `${state.pubs.length} demo pubs ready · connect PostgreSQL for the full London dataset`; renderAll(); } catch { $('#status').textContent = `The pub list is unavailable. Start the API and check ${API_URL}.`; updateCounts(); } } }
function renderMap() { if (!window.L) return; $('#map').hidden = false; if (!state.map) { state.map = L.map('map').setView([51.5074, -0.1278], 12); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '© OpenStreetMap contributors' }).addTo(state.map); state.markers = L.layerGroup().addTo(state.map); } state.markers.clearLayers(); visiblePubs().slice(0, 200).forEach((pub) => { if (typeof pub.latitude !== 'number') return; const marker = L.marker([pub.latitude, pub.longitude]).bindPopup(`<strong>${pub.name.replaceAll('<','&lt;')}</strong><br>${(pub.address || '').replaceAll('<','&lt;')}`); state.markers.addLayer(marker); }); state.map.invalidateSize(); window.setTimeout(() => $('#map').scrollIntoView({ behavior: 'smooth', block: 'start' }), 60); }
function setRoute(route) { const explore = route === 'explore'; $('#explore-view').hidden = !explore; $('#passport-view').hidden = explore; document.querySelectorAll('.nav-link').forEach((button) => button.classList.toggle('active', button.dataset.route === route)); if (!explore) renderPassport(); window.scrollTo({ top: 0, behavior: 'smooth' }); }

$('#search-form').addEventListener('submit', (event) => { event.preventDefault(); state.query = $('#query').value; void getRecommendations(); }); $('#query').addEventListener('input', () => { state.query = $('#query').value; state.aiResults = null; state.aiContext = null; }); $('#clear-search').addEventListener('click', () => { $('#query').value = ''; state.query = ''; state.aiResults = null; state.aiContext = null; state.filtered = state.pubs; $('#status').textContent = `${state.pubs.length} pubs ready to explore`; renderResults(); $('#query').focus(); }); document.querySelectorAll('[data-query]').forEach((button) => button.addEventListener('click', () => { $('#query').value = button.dataset.query; state.query = button.dataset.query; void getRecommendations(); })); document.querySelectorAll('[data-route]').forEach((button) => button.addEventListener('click', (event) => { event.preventDefault(); setRoute(button.dataset.route); })); document.querySelectorAll('.view-tab').forEach((button) => button.addEventListener('click', () => { state.view = button.dataset.view; document.querySelectorAll('.view-tab').forEach((item) => item.classList.toggle('active', item === button)); $('#results').hidden = state.view === 'map'; $('#map').hidden = state.view !== 'map'; if (state.view === 'map') renderMap(); })); $('#map-toggle').addEventListener('click', () => { state.view = 'map'; document.querySelector('[data-view="map"]').click(); }); $('#close-detail').addEventListener('click', () => $('#detail-dialog').close()); $('#detail-dialog').addEventListener('click', (event) => { if (event.target === $('#detail-dialog')) $('#detail-dialog').close(); }); loadPubs();
